spring.application.name=demo
spring.datasource.url=jdbc:sqlite:g3_chatbot.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# File upload properties
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Gemini API Configurations
gemini.api.key=${GEMINI_API_KEY}
gemini.model.chat=gemini-2.5-flash
gemini.model.embedding=gemini-embedding-001
